query ($id: UUID!) {
  result: facilityById(id: $id) {
    __typename
    ...Facility
  }
}

fragment Facility on FacilityGQLModel {
  id
  lastchange
  name  
  nameEn
  label
  address
  valid
  capacity
  geometry
  geolocation
  type { id name }
  subFacilities { id }
  masterFacility { id }
  createdby { id }
  changedby { id }
  rbacobject { id }
}
